//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITYPOLYGONHIERARCHY
    {
        public long IL_ID { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string ISGEO { get; set; }
        public string LOVTOWN { get; set; }
    }
}
