//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeocoderEntities : DbContext
    {
        public GeocoderEntities()
            : base("name=GeocoderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITYPOLYGONHIERARCHY> CITYPOLYGONHIERARCHY { get; set; }
        public virtual DbSet<GEOLOC_IL> GEOLOC_IL { get; set; }
        public virtual DbSet<GEOLOC_ILCE> GEOLOC_ILCE { get; set; }
        public virtual DbSet<HINTCITYGEOCITYCR> HINTCITYGEOCITYCR { get; set; }
        public virtual DbSet<HINTERLAND_SUBFIELDS> HINTERLAND_SUBFIELDS { get; set; }
        public virtual DbSet<HINTTOWNGEOTOWNCR> HINTTOWNGEOTOWNCR { get; set; }
        public virtual DbSet<IDARI_SINIR_YOL> IDARI_SINIR_YOL { get; set; }
        public virtual DbSet<IL> IL { get; set; }
        public virtual DbSet<ILCE> ILCE { get; set; }
        public virtual DbSet<KAPI> KAPI { get; set; }
        public virtual DbSet<LOVPOLYGONLEVEL> LOVPOLYGONLEVEL { get; set; }
        public virtual DbSet<LOVPOLYGONTYPE> LOVPOLYGONTYPE { get; set; }
        public virtual DbSet<MAHALLE> MAHALLE { get; set; }
        public virtual DbSet<MAHALLEAREA> MAHALLEAREA { get; set; }
        public virtual DbSet<MAP_DATA30> MAP_DATA30 { get; set; }
        public virtual DbSet<MAP_POIINFO> MAP_POIINFO { get; set; }
        public virtual DbSet<POI_ARAS> POI_ARAS { get; set; }
        public virtual DbSet<POI_INFO> POI_INFO { get; set; }
        public virtual DbSet<TOWNPOLYGONHIERARCHY> TOWNPOLYGONHIERARCHY { get; set; }
        public virtual DbSet<YOL> YOL { get; set; }
        public virtual DbSet<SAMPLEADDRESS> SAMPLEADDRESS { get; set; }
        public virtual DbSet<SAMPLEADDRESSRESULT> SAMPLEADDRESSRESULT { get; set; }
    }
}
