//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEOLOC_ILCE
    {
        public Nullable<long> ILCE_ID { get; set; }
        public Nullable<long> IL_ID { get; set; }
        public string ILCE_ADI { get; set; }
        public string XCOOR { get; set; }
        public string YCOOR { get; set; }
        public string IL_ILCE { get; set; }
        public long MI_PRINX { get; set; }
        public string MI_STYLE { get; set; }
        public Nullable<bool> ZONE { get; set; }
    }
}
