//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINTTOWNGEOTOWNCR
    {
        public Nullable<System.Guid> HINTCITYID { get; set; }
        public Nullable<decimal> IL_ID { get; set; }
        public Nullable<long> GEOLOC_IL_ID { get; set; }
        public System.Guid HINTTOWNID { get; set; }
        public decimal ILCE_ID { get; set; }
        public string ILCE_ADI { get; set; }
        public Nullable<long> GEOLOC_ILCE_ID { get; set; }
        public Nullable<System.DateTime> AUDIT_CREATE_DATE { get; set; }
        public Nullable<int> AUDITCREATEDBY { get; set; }
        public Nullable<short> AUDITCREATEUNITID { get; set; }
        public Nullable<System.DateTime> AUDIT_MODIFY_DATE { get; set; }
        public Nullable<int> AUDITMODIFIEDBY { get; set; }
        public Nullable<short> AUDITMODIFYUNITID { get; set; }
        public string AUDIT_DELETED { get; set; }
        public string APPLICATION_VERSION { get; set; }
        public Nullable<short> APPLICATIONID { get; set; }
        public string ACTIVE { get; set; }
    }
}
