//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAPI
    {
        public string KAPI_ADI { get; set; }
        public decimal KAPI_ID { get; set; }
        public string KAPI_NO { get; set; }
        public Nullable<decimal> MAHALLE_ID { get; set; }
        public string POSTA_KODU { get; set; }
        public string XCOOR { get; set; }
        public string YCOOR { get; set; }
        public Nullable<decimal> YOL_ID { get; set; }
    }
}
