//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAHALLE
    {
        public Nullable<decimal> ILCE_ID { get; set; }
        public string MAHALLE_ADI { get; set; }
        public decimal MAHALLE_ID { get; set; }
        public Nullable<bool> TYPE { get; set; }
        public string POSTA_KODU { get; set; }
        public string XCOOR { get; set; }
        public string YCOOR { get; set; }
    }
}
