//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_POIINFO
    {
        public System.Guid MAPDATAID { get; set; }
        public string SONUC { get; set; }
        public string SONUC_ILCELI { get; set; }
        public string XCOOR { get; set; }
        public string YCOOR { get; set; }
        public Nullable<decimal> MAHALLE_ID { get; set; }
        public Nullable<decimal> YOL_ID { get; set; }
        public Nullable<decimal> ILCE_ID { get; set; }
        public Nullable<decimal> IL_ID { get; set; }
        public Nullable<decimal> POI_ID { get; set; }
        public string NAME { get; set; }
        public string NAME_FULL { get; set; }
        public Nullable<decimal> LOVDATAPRIORITY { get; set; }
        public Nullable<System.DateTime> AUDIT_CREATE_DATE { get; set; }
        public Nullable<int> AUDITCREATEDBY { get; set; }
        public Nullable<short> AUDITCREATEUNITID { get; set; }
        public Nullable<System.DateTime> AUDIT_MODIFY_DATE { get; set; }
        public Nullable<int> AUDITMODIFIEDBY { get; set; }
        public Nullable<short> AUDITMODIFYUNITID { get; set; }
        public string AUDIT_DELETED { get; set; }
        public string APPLICATION_VERSION { get; set; }
        public Nullable<short> APPLICATIONID { get; set; }
    }
}
