//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI_ARAS
    {
        public decimal ID { get; set; }
        public string STANDARD_NAME { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> SUB_TYPE { get; set; }
        public string PLACE_NAME { get; set; }
        public string STREET_NAME { get; set; }
        public string STREET_TYPE { get; set; }
        public string HSN { get; set; }
        public string POSTAL_CODE { get; set; }
        public Nullable<decimal> IL_ID { get; set; }
        public Nullable<decimal> ILCE_ID { get; set; }
        public Nullable<decimal> MAHALLE_ID { get; set; }
        public string XCOOR { get; set; }
        public string YCOOR { get; set; }
        public Nullable<System.DateTime> AUDIT_CREATE_DATE { get; set; }
        public Nullable<int> AUDITCREATEDBY { get; set; }
        public Nullable<int> AUDITCREATEUNITID { get; set; }
        public Nullable<System.DateTime> AUDIT_MODIFY_DATE { get; set; }
        public Nullable<int> AUDITMODIFIEDBY { get; set; }
        public Nullable<int> AUDITMODIFYUNITID { get; set; }
        public string AUDIT_DELETED { get; set; }
        public string APPLICATION_VERSION { get; set; }
        public Nullable<int> APPLICATIONID { get; set; }
    }
}
