//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocoderAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLEADDRESSRESULT
    {
        public System.Guid ID { get; set; }
        public string XCOORYANDEX { get; set; }
        public string YCOORYANDEX { get; set; }
        public string YANDEXTIME { get; set; }
        public string XCOORGOOGLE { get; set; }
        public string YCOORGOOGLE { get; set; }
        public string GOOGLETIME { get; set; }
        public string XCOORMY { get; set; }
        public string YCOORMY { get; set; }
        public string MYTIME { get; set; }
    }
}
